version: "2"

services:
  mariadb:
    image: wodby/mariadb
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 60s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    # volumes:
    #   - mysql-data:/var/lib/mysql
    #   - ./db:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    # image: wodby/drupal-php:$PHP_TAG # Allowed: 7.0, 5.6. Specify build number to ensure each team member is using the same version of the container.
    build: ./docker-php/
    # build:
    #   context: docker-php
    #   dockerfile: Dockerfile
    # image: myphp
    container_name: "${PROJECT_NAME}_php"
    # user: root
    # command: "php-fpm -R"
    environment:
      # PHP_FPM_USER: root
      # PHP_FPM_GROUP: root
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: oetinger
      # PHP_DOCROOT: web # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 1
      # PHP_XDEBUG_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
    volumes:
      - ./thunder/:/var/www/html

  nginx:
    image: wodby/drupal-nginx
    container_name: "${PROJECT_NAME}_nginx"
    environment:
      NGINX_SERVER_NAME: oetinger
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: docroot # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot
    volumes_from:
      - php
    ports:
      - "80:80"

  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - "8002:8025"

  selenium:
   container_name: selenium
   image: selenium/standalone-firefox:2.53.1

  node-php-composer:
   #image: savaslabs/node-php-composer:1.2
   build:
      context: docker-node
      dockerfile: Dockerfile
   container_name: "${PROJECT_NAME}_node-php-composer"
   ports:
     - "3050:3000"
     - "3001:3001"
   tty: true
   volumes_from:
     - php

  

# volumes:
#   mysql-data:
#     driver: local